# -*- coding: utf-8 -*-
"""
Post-processing script for Poynting Vector Calculation

This script processes the HDF5 files generated from openEMS, calculates the Poynting vector,
and generates a log-scale image of the Poynting vector's magnitude.

Tested with:
 - Python 3.10
 - openEMS v0.0.35+
 - h5py for HDF5 file handling

(c) 2023 Your Name
"""

import os
import numpy as np
import h5py
import matplotlib.pyplot as plt
import matplotlib
import tempfile

matplotlib.use('Agg')  # Use non-interactive backend suitable for headless servers


def calculate_poynting_vector(E_field, H_field):
    """
    Calculate the Poynting vector (S = E x H) from E-field and H-field components.
    Args:
    - E_field: numpy array of shape (3, 35, 35, 1) for [Ex, Ey, Ez]
    - H_field: numpy array of shape (3, 35, 35, 1) for [Hx, Hy, Hz]

    Returns:
    - poynting_vector: numpy arrays Sx, Sy, Sz
    """
    # Access the components of the E-field and H-field
    Ex, Ey, Ez = E_field[0, :, :, 0], E_field[1, :, :, 0], E_field[2, :, :, 0]
    Hx, Hy, Hz = H_field[0, :, :, 0], H_field[1, :, :, 0], H_field[2, :, :, 0]

    # Calculate the Poynting vector components
    Sx = Ey * Hz - Ez * Hy
    Sy = Ez * Hx - Ex * Hz
    Sz = Ex * Hy - Ey * Hx

    return Sx, Sy, Sz


def plot_poynting_magnitude(sim_path, E_h5_file, H_h5_file, time_step='00000168', save_fig=True):
    # Load the E-field and H-field data from HDF5 files for the specific time step
    with h5py.File(os.path.join(sim_path, E_h5_file), 'r') as e_file, \
            h5py.File(os.path.join(sim_path, H_h5_file), 'r') as h_file:

        # Extract the E-field and H-field data for the given time step
        E_field = np.array(e_file['FieldData']['TD'][time_step])  # E-field components [Ex, Ey, Ez]
        H_field = np.array(h_file['FieldData']['TD'][time_step])  # H-field components [Hx, Hy, Hz]

    # check if the e-field and h-field data have the same shape

    # Calculate the Poynting vector components
    Sx, Sy, Sz = calculate_poynting_vector(E_field, H_field)

    # Calculate the magnitude of the Poynting vector
    S_magnitude = np.sqrt(Sx ** 2 + Sy ** 2 + Sz ** 2)

    # Set up the figure for the log-scale image
    plt.figure(figsize=(10, 8))
    plt.imshow(
        np.log10(S_magnitude[:, :, 0]),  # Log scale of the Poynting vector magnitude in the yz-plane (slice at x=0)
        origin='lower',  # Origin at the bottom-left
        aspect='auto',  # Aspect ratio
        cmap='jet',  # Color map
        norm=matplotlib.colors.LogNorm(vmin=S_magnitude.min() + 1e-9, vmax=S_magnitude.max())
    )
    plt.colorbar(label='Poynting Vector Magnitude (log scale)')
    plt.title('Poynting Vector Magnitude (Log-Scale Image) in yz-plane')
    plt.xlabel('y-axis Index')
    plt.ylabel('z-axis Index')
    plt.grid(False)

    # Save the image
    if save_fig:
        fig_file_path = os.path.join(sim_path, f'poynting_log_scale_image_{time_step}.png')
        plt.savefig(fig_file_path)
        print(f"Log-scale image of Poynting vector magnitude saved as: {fig_file_path}")
    else:
        plt.show()

    plt.close()


if __name__ == '__main__':
    # Set the simulation path and HDF5 filenames
    sim_path = os.path.join(tempfile.gettempdir(), 'RCS_Sphere_Simulation_Backscatter_Vis')

    # Replace these with the actual HDF5 filenames generated by your simulation
    E_h5_file = 'E_dump_back.h5'
    H_h5_file = 'H_dump_back.h5'

    if not os.path.exists(sim_path):
        print(f"Simulation directory not found: {sim_path}")
    else:
        plot_poynting_magnitude(sim_path, E_h5_file, H_h5_file, time_step='00000000')
