# -*- coding: utf-8 -*-
"""
Post-processing script for Poynting Vector Calculation using PyVista

This script processes the .vtr files generated from openEMS, calculates the Poynting vector,
and generates a log-scale image of the Poynting vector's magnitude.

Tested with:
 - Python 3.10
 - openEMS v0.0.35+
 - pyvista, numpy for VTR file handling

(c) 2023 Your Name
"""

import os
import numpy as np
import pyvista as pv
import matplotlib.pyplot as plt
import matplotlib
import tempfile
from field_processing import read_vtr_file, calculate_poynting_vector

matplotlib.use('Agg')  # Use non-interactive backend suitable for headless servers

def plot_poynting_magnitude(sim_path, e_vtr_file, h_vtr_file, desired_direction=[-1, 0, 0], bias_factor=3, save_fig=True):
    # Load the E-field and H-field data from VTR files
    E_field = read_vtr_file(os.path.join(sim_path, e_vtr_file), field='E-Field')
    H_field = read_vtr_file(os.path.join(sim_path, h_vtr_file), field='H-Field')

    E_field = np.array(E_field)
    H_field = np.array(H_field)

    # Calculate the Poynting vector components
    Sx, Sy, Sz = calculate_poynting_vector(E_field, H_field)

    # Normalize the desired direction
    desired_direction = np.array(desired_direction)
    desired_direction = desired_direction / np.linalg.norm(desired_direction)

    # Compute the dot product between Poynting vector and desired direction
    S_projection = Sx * desired_direction[0] + Sy * desired_direction[1] + Sz * desired_direction[2]

    # Apply bias by raising the absolute value of the dot product to the power of 'bias_factor'
    S_biased = np.sign(S_projection) * np.abs(S_projection) ** bias_factor

    # Clip negative values or set them to zero (if you only want to show waves going back along [-1, 0, 0])
    S_biased = np.maximum(S_biased, 0)

    # Add a small epsilon to avoid log(0)
    epsilon = 1e-40
    S_biased_log = np.log10(S_biased + epsilon)

    # Print the range to verify the data
    print("S_biased range:", np.min(S_biased), np.max(S_biased))

    # Set up the figure for the log-scale image
    plt.figure(figsize=(10, 8))
    plt.imshow(
        S_biased_log,  # Log scale of the biased Poynting vector projection
        origin='lower',  # Origin at the bottom-left
        aspect='auto',  # Aspect ratio
        cmap='jet',  # Color map
    )
    plt.colorbar(label=f'Biased Poynting Vector (log scale) [Bias Factor: {bias_factor}]')
    plt.title(f'Poynting Vector Projection with Bias (Log-Scale) in yz-plane')
    plt.xlabel('y-axis Index')
    plt.ylabel('z-axis Index')
    plt.grid(False)

    # Save the image
    if save_fig:
        fig_file_path = os.path.join(sim_path, f'biased_poynting_log_scale_image.png')
        plt.savefig(fig_file_path)
        print(f"Log-scale image of biased Poynting vector projection saved as: {fig_file_path}")
    else:
        plt.show()

    plt.close()




if __name__ == '__main__':
    # Set the simulation path and VTR filenames
    sim_path = os.path.join(tempfile.gettempdir(), 'RCS_Corner_Reflector_Simulation')

    # Replace these with the actual VTR filenames generated by your simulation
    e_vtr_file = 'E_dump_outside_0000000046.vtr'
    h_vtr_file = 'H_dump_outside_0000000046.vtr'

    if not os.path.exists(sim_path):
        print(f"Simulation directory not found: {sim_path}")
    else:
        plot_poynting_magnitude(sim_path, e_vtr_file, h_vtr_file)
